baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

pagination.pagerSize = 2
enableSearch = true

[menus]
  [[menus.main]]
    name = "n3s0 || journal"
    title = "Journal"
    url = "/"
    weight = 1
  [[menus.main]]
    name = 'Journal'
    title = 'Journal'
    url = '/journal'
    weight = 2
  [[menus.main]]
    name = 'Build'
    title = 'Build'
    url = '/build'
    weight = 3
  [[menus.main]]
    name = 'Notes'
    title = 'Notes'
    url = '/notes'
    weight = 4
  [[menus.main]]
    name = 'Projects'
    title = 'Projects'
    url = '/projects'
    weight = 5
  [[menus.main]]
    name = 'Bookmarks'
    title = 'Bookmarks'
    url = '/bookmarks'
    weight = 10
  [[menus.main]]
    name = 'Contact'
    title = 'Contact'
    url = '/contact'
    weight = 11
  [[menus.main]]
    name = 'Github'
    url = 'https://github.com/n3s0/'
    weight = 12
  [[menus.main]]
    name = 'GitLab'
    url = 'https://gitlab.com/n3s0/'
    weight = 13
  [[menus.main]]
    name = 'Search'
    title = 'Search'
    url = '/search'
    weight = 14
  [[menus.main]]
    name = 'RSS'
    title = 'RSS'
    url = '/index.xml'
    weight = 15
  [[menus.footer]]
    name = 'Contact'
    title = 'Contact'
    url = '/contact/'
    weight = 1

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
